### ISSUE TITLE
[Bug]: Rescue Cushions

### ISSUE THREAD

**Issue by zenabzz** [CMGStudios/issue-tracker#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Placing down Recsue Cushions and Jumping on them does not negate fall damage and you die also you fall straight through it.

### Expected behaviour

Jump on the cushion without falling through it and not taking any kind of fall damage

### Steps to reproduce

1.clock on LFB
2. /lfb>Tools>Setup Rescue Cushion
3. Jump on it from a high Place
4. Phase through it and Die.

Clip:
https://streamable.com/9n91n0

### Any Texture Packs? (If so list)

None

### CMG User ID

71613

**Comment by alfiellds** [comment]
This has been fixed - thank you for the report.

**Comment by zenabzz** [comment]
This issue is still ongoing, you still phase through the coushin and fall to your death.
