### ISSUE TITLE
[Bug]: Mirror Park House 10

### ISSUE THREAD

**Issue by Street1112** [CMGStudios/issue-tracker#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

MLO can't let anyone walk in like something is blocking the door and you can't get up the stairs

### Expected behaviour

MLO can't let anyone walk in like something is blocking the door and you can't get up the stairs

### Steps to reproduce

.

### CMG User ID

958

**Comment by crazychris2404** [comment]
Confirmed
Thanks for the report

**Comment by Street1112** [comment]
Hi, Do you have an ETA on when it will be fixed as spent 50m on a house that doesn't work?

**Comment by packfile** [comment]
Thanks for the report, this has been fixed from the next scheduled restart

**Comment by Street1112** [comment]
house still isn't fixed clip attached https://medal.tv/games/gta-v/clips/1bTGW6FfWApyPz/d1337Muwfxna?invite=cr-MSxIOWYsMTU3MDE1NzI4LA
